# Android & Kotlin Settings
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.caching=true
-Dfile.encoding=UTF-8

# Temp Directory
-Djava.io.tmpdir=/data/data/com.itsaky.androidide/files/usr/tmp

# Single-Threaded Memory Cap
org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=256m
org.gradle.parallel=false
org.gradle.workers.max=1
